In [43]:
import numpy as np

In [44]:
error = np.array([
    [51.35335922, 51.6334343, 51.32881927, 51.1204071, 50.91790009,
     50.72195435, 50.54049301, 50.37900925, 50.23846436, 50.12049484,
     50.02666855, 49.96744537, 49.95156479, 49.9884491, 50.08406448,
     50.2577095, 50.12652969, 50.01920319, 49.91918182, 49.82745743,
     49.93736267, 49.01161194, 48.95986557, 0., 0.,
     0., 0., 0., 0., 0.],
    [45.73011398, 45.50281906, 45.33833694, 45.25089264, 45.21937561,
     45.24537659, 45.33146667, 45.48620605, 45.7168808, 46.10063934,
     46.64596176, 47.42542648, 48.43967819, 49.26279068, 50.16548157,
     50.28884888, 50.74268723, 52.22551727, 52.22296143, 51.87726212,
     52.03133392, 52.19487381, 52.36346817, 52.53575516, 51.95433807,
     52.6297226, 51.71553802, 52.28501511, 52.41733932, 51.612854],
    [74.93945312, 73.04078674, 70.76474762, 69.36988068, 68.35562134,
     67.47942352, 66.3837204, 65.61459351, 64.24323273, 64.01303864,
     63.71177673, 63.01027298, 62.52959061, 62.16213989, 62.69816589,
     63.33938599, 63.0675621, 62.31041336, 62.08007812, 61.94081497,
     61.17954636, 60.5858345, 62.10678482, 61.82591629, 61.66379929,
     61.42486572, 60.93463516, 61.52167892, 61.3787117, 61.13344193],
    [48.44749832, 46.74816895, 44.88916397, 42.9418602, 40.93766785,
     39.12932587, 39.2185936, 39.88443756, 42.04213333, 43.17124939,
     43.46310425, 43.2456665, 43.51581573, 43.31405258, 43.5758667,
     43.37654495, 43.64353943, 43.4445343, 43.70614624, 44.09214783,
     43.80128098, 43.1638031, 42.68924713, 43.02801514, 42.8826828,
     43.23279572, 42.61919785, 42.2074585, 42.56698227, 42.48870087],
    [87.64406586, 90.07849121, 89.47576904, 91.47328949, 90.68669891,
     90.58013916, 90.4178772, 93.57175446, 92.40743256, 92.31506348,
     92.5067215, 92.741539, 96.26180267, 95.06726074, 94.58956146,
     98.82562256, 99.91430664, 100.76468658, 101.26818848, 101.63755035,
     98.72381592, 100.95568848, 101.31044769, 101.70553589, 102.15146637,
     102.60510254, 100.28238678, 101.71157074, 103.10744476, 102.3486557],
    [59.55375671, 58.8314476, 59.36095047, 59.41041565, 61.07491684,
     59.79533768, 59.58645248, 59.5149498, 59.50217056, 59.53222656,
     59.64473724, 59.79933167, 59.92670822, 60.04311752, 60.90756989,
     59.95183182, 60.84743881, 59.92388535, 60.69966888, 60.75791931,
     60.90950775, 61.05059814, 61.18104172, 62.06941223, 61.63490295,
     61.72659683, 61.8185463, 61.90916443, 62.39787292, 62.14432144],
    [59.52237701, 57.15004349, 54.61872101, 51.96687698, 49.10414886,
     46.42461014, 47.16746902, 45.12368393, 46.08885956, 44.72718048,
     44.51218796, 44.21450806, 45.56443024, 46.03029633, 45.82027817,
     45.68484497, 45.51569748, 45.49637985, 45.34362411, 45.43753815,
     45.27556992, 45.51791382, 46.17259979, 45.93326569, 46.45520401,
     46.05463028, 45.76016998, 46.41657257, 47.14594269, 46.77830124],
    [72.52087402, 71.69759369, 71.3354187, 71.24938202, 71.31108856,
     71.49585724, 71.74923706, 72.0679245, 72.45823669, 72.34650421,
     71.9994812, 71.45462036, 70.79074097, 70.08621979, 69.38161469,
     68.6714859, 67.92040253, 66.1669693, 64.76409149, 63.53514862,
     62.3976593, 61.31300735, 60.26959229, 59.30284882, 58.94680405,
     57.37291718, 57.61585236, 57.84185791, 58.16703796, 57.40366745],
    [68.44661713, 70.88573456, 70.38379669, 71.02737427, 71.46213531,
     71.73442078, 71.39627838, 71.39548492, 72.31581116, 72.00255585,
     71.844841, 71.61184692, 71.56374359, 71.45295715, 71.29312897,
     71.29186249, 71.20400238, 71.04660797, 71.06726837, 71.0062561,
     0., 0., 0., 0., 0.,
     0., 0., 0., 0., 0.]
    ])

error.shape

(9, 30)

In [45]:
# calculate mean
mean = np.mean(error, axis=0)
mean

array([63.12867949, 62.84094662, 61.9439693 , 61.53448656, 61.00772815,
       60.28960504, 60.19906531, 60.33756044, 60.55702464, 60.48099475,
       60.48394224, 60.38562859, 60.94934167, 60.82303153, 60.94619242,
       61.2986819 , 61.44246292, 61.26646635, 61.23013433, 61.1235661 ,
       52.69511965, 52.64370346, 52.78367191, 47.37786102, 47.29879973,
       47.22740343, 46.74959183, 47.09925758, 47.4645924 , 47.10110474])

In [46]:
# fill zeros using the last non-zero value
for i in range(error.shape[0]):
    for j in range(error.shape[1]):
        if error[i, j] == 0.:
            error[i, j] = error[i, j-1]

error

array([[ 51.35335922,  51.6334343 ,  51.32881927,  51.1204071 ,
         50.91790009,  50.72195435,  50.54049301,  50.37900925,
         50.23846436,  50.12049484,  50.02666855,  49.96744537,
         49.95156479,  49.9884491 ,  50.08406448,  50.2577095 ,
         50.12652969,  50.01920319,  49.91918182,  49.82745743,
         49.93736267,  49.01161194,  48.95986557,  48.95986557,
         48.95986557,  48.95986557,  48.95986557,  48.95986557,
         48.95986557,  48.95986557],
       [ 45.73011398,  45.50281906,  45.33833694,  45.25089264,
         45.21937561,  45.24537659,  45.33146667,  45.48620605,
         45.7168808 ,  46.10063934,  46.64596176,  47.42542648,
         48.43967819,  49.26279068,  50.16548157,  50.28884888,
         50.74268723,  52.22551727,  52.22296143,  51.87726212,
         52.03133392,  52.19487381,  52.36346817,  52.53575516,
         51.95433807,  52.6297226 ,  51.71553802,  52.28501511,
         52.41733932,  51.612854  ],
       [ 74.93945312,  73.0407

In [47]:
# calculate mean
mean = np.mean(error, axis=0)
mean

array([63.12867949, 62.84094662, 61.9439693 , 61.53448656, 61.00772815,
       60.28960504, 60.19906531, 60.33756044, 60.55702464, 60.48099475,
       60.48394224, 60.38562859, 60.94934167, 60.82303153, 60.94619242,
       61.2986819 , 61.44246292, 61.26646635, 61.23013433, 61.1235661 ,
       60.58470366, 60.53328747, 60.67325592, 60.7074301 , 60.6283688 ,
       60.5569725 , 60.0791609 , 60.42882665, 60.79416148, 60.43067381])

In [48]:
np.mean(mean)

60.92287832174074

In [49]:
error_avg = np.array([
    63.12867949, 62.84094662, 61.9439693, 61.53448656, 61.00772815, 60.28960503,
    60.19906531, 60.33756044, 60.55702464, 60.48099475, 60.48394224, 60.38562859,
    60.94934167, 60.82303153, 60.94619242, 61.29868189, 61.44246292, 61.26646635,
    61.23013433, 61.1235661, 52.69511965, 52.64370346, 52.78367191, 47.37786102,
    47.29879973, 47.22740343, 46.74959183, 47.09925758, 47.4645924, 47.10110474
])
error_avg.shape

(30,)